learn1/urls.py
from django.conf.urls import url
from django.contrib import admin
from boards import views

urlpatterns = [
    url(r'^boards/$', views.home, name='home'),
    url(r'^board/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^board/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics')
    starter = models.ForeignKey(User, related_name='topics')

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, related_name='+')

boards/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import Board, Topic, Post

# Create your views here.
def home(request):
    all_boards = Board.objects.all()
    return render(request, 'home.html', {'boards': all_boards})

def board_topics(request, pk):
    try:
        boardObj = Board.objects.get(pk=pk)
    except Board.DoesNotExist:
        raise Http404

    return render(request, 'topics.html', {'board': boardObj})

def new_topic(request, pk):
    boardObj = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']

        user = User.objects.first()

        topic = Topic.objects.create(
            subject=subject,
            board=boardObj,
            starter=user
        )

        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=user
        )
        return redirect('board_topics', pk=boardObj.pk)

    return render(request, 'new_topic.html', {'board':boardObj})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}Django Boards{% endblock %}
        </title>
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    </head>

    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">Django Boards</a>
            </div>
        </nav>

        <div class="container">
            <ol class="breadcrumb my-4">
                {% block breadcrumb %}
                {% endblock %}
            </ol>

            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Board</th>
                <th>Posts</th>
                <th>Topics</th>
                <th>Last Post</th>
            </tr>
        </thead>

        <tbody>
            {% for board in boards %}
                <tr>
                    <td>
                        <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
                        <small class="text-muted d-block">{{ board.description }}</small>
                    </td>
                    <td class="align-middle">0</td>
                    <td class="align-middle">0</td>
                    <td></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a new Topic{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New Topic</li>
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_subject">Subject</label>
            <input type="text" class="form-control" id="id_subject" name="subject">
        </div>
        <div class="form-group">
            <label for="id_message">Message</label>
            <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Post</button>
    </form>

{% endblock %}

templates/topics.html
{% extends 'base.html' %}

{% block title %}
    {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New Topic</a>
    </div>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Topics</th>
                <th>Starter</th>
                <th>Replies</th>
                <th>Views</th>
                <th>Last Update</th>
            </tr>
        </thead>
        <tbody>
            {% for topic in board.topics.all %}
                <tr>
                    <td>{{ topic.subject }}</td>
                    <td>{{ topic.starter.username }}</td>
                    <td>0</td>
                    <td>0</td>
                    <td>{{ topic.last_updated }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}